name: ci
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 -m pip install tox
      - name: Run linter
        run: make lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 -m pip install tox
      - name: Build charm
        run: make build
      - name: Upload charm artifact
        uses: actions/upload-artifact@v1
        with:
          name: charm
          path: /tmp/charm-builds/ubuntu-lite
  test:
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        juju_channel:
          - 2.8/stable
          - 2.9/stable
          - 3.0/stable
        test_bundles:
          - focal-bundle
          - jammy-bundle
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 -m pip install tox
      - name: Download charm artifact
        uses: actions/download-artifact@v3
        with:
          name: charm
          path: /tmp/charm-builds/ubuntu-lite
      # Workarounds for https://github.com/actions/upload-artifact/issues/38
      - run: chmod +x -R /tmp/charm-builds/ubuntu-lite/hooks
      - name: Set up LXD
        run: |
          sudo usermod --append --groups lxd $(whoami)
          sudo su $(whoami) -c 'lxd init --auto'
          sudo su $(whoami) -c 'lxc network set lxdbr0 ipv6.address none'
      - name: Set up juju
        run: |
          sudo snap install juju --classic --channel=${{ matrix.juju_channel }}
          sudo su $(whoami) -c 'juju bootstrap localhost --no-gui'
      - name: Run deploy
        run: make deploy-${{ matrix.test_bundles }}
      - name: Run jujuna tests
        run: make test-${{ matrix.test_bundles }}
      - name: Display juju debug log on failure
        run: juju debug-log --lines 100
        if: failure()
